# ROS2 Node Manager - Server Configuration
#
# Configure your Docker containers here.
# The first server in the list will be used for auto-connection on startup.

servers:
  - id: local
    name: "Local Docker"
    type: local
    container: tram_autoware

  - id: server_30639
    name: "Tram_30639"
    type: ssh
    host: 192.168.242.7
    port: 22
    user: tram
    container: tram_autoware
    password: "1qaz@WSX"

  # Another remote server (example)
  # - id: tram-test
  #   name: "Tram Test Server"
  #   type: ssh
  #   host: 10.0.0.50
  #   port: 22
  #   user: autopilot
  #   container: autoware_container
  #   ssh_key: ~/.ssh/tram_key
